
ALTER TABLE BOOK
	ADD (CONSTRAINT R_40 FOREIGN KEY (ctgy_id) REFERENCES CATEGORY (ctgy_id));



ALTER TABLE BOOK
	ADD (CONSTRAINT R_48 FOREIGN KEY (member_id) REFERENCES MEMBER (member_id) ON DELETE SET NULL);



ALTER TABLE BOOK_ATTACH
	ADD (CONSTRAINT R_2 FOREIGN KEY (book_id) REFERENCES BOOK (book_id));



ALTER TABLE BOOK_CONFIRM
	ADD (CONSTRAINT R_14 FOREIGN KEY (book_id) REFERENCES BOOK (book_id));



ALTER TABLE BOOK_REPLY
	ADD (CONSTRAINT R_3 FOREIGN KEY (book_id) REFERENCES BOOK (book_id));



ALTER TABLE BUCKET_BOOK
	ADD (CONSTRAINT R_23 FOREIGN KEY (member_id) REFERENCES MEMBER (member_id));



ALTER TABLE BUCKET_BOOK
	ADD (CONSTRAINT R_42 FOREIGN KEY (book_id) REFERENCES BOOK (book_id));



ALTER TABLE CATEGORY
	ADD (CONSTRAINT R_51 FOREIGN KEY (mcnfm_id) REFERENCES MANAGER_CONFIRM (mcnfm_id) ON DELETE SET NULL);



ALTER TABLE COMMUNITY
	ADD (CONSTRAINT R_43 FOREIGN KEY (member_id) REFERENCES MEMBER (member_id));



ALTER TABLE COMMUNITY_REPLY
	ADD (CONSTRAINT R_44 FOREIGN KEY (cmmnty_id) REFERENCES COMMUNITY (cmmnty_id));



ALTER TABLE LEND
	ADD (CONSTRAINT R_20 FOREIGN KEY (member_id) REFERENCES MEMBER (member_id));



ALTER TABLE LEND_BOOKS
	ADD (CONSTRAINT R_21 FOREIGN KEY (lend_id) REFERENCES LEND (lend_id));



ALTER TABLE LEND_BOOKS
	ADD (CONSTRAINT R_22 FOREIGN KEY (book_id) REFERENCES BOOK (book_id));



ALTER TABLE LOGIN_HISTORY
	ADD (CONSTRAINT R_16 FOREIGN KEY (member_id) REFERENCES MEMBER (member_id));



ALTER TABLE MANAGER_CONFIRM
	ADD (CONSTRAINT R_13 FOREIGN KEY (member_id) REFERENCES MEMBER (member_id));



ALTER TABLE PAY_HISTORY
	ADD (CONSTRAINT R_52 FOREIGN KEY (mcnfm_id) REFERENCES MANAGER_CONFIRM (mcnfm_id));



ALTER TABLE REVIEW
	ADD (CONSTRAINT R_6 FOREIGN KEY (book_id) REFERENCES BOOK (book_id));



ALTER TABLE REVIEW_REPLY
	ADD (CONSTRAINT R_5 FOREIGN KEY (review_id) REFERENCES REVIEW (review_id));



ALTER TABLE SCHEDULE
	ADD (CONSTRAINT R_25 FOREIGN KEY (member_id) REFERENCES MEMBER (member_id));



ALTER TABLE SCHEDULE
	ADD (CONSTRAINT R_27 FOREIGN KEY (book_id) REFERENCES BOOK (book_id));



ALTER TABLE SCODES
	ADD (CONSTRAINT R_15 FOREIGN KEY (lcode) REFERENCES LCODES (lcode));



ALTER TABLE SUBSCRIPTION
	ADD (CONSTRAINT R_49 FOREIGN KEY (member_id) REFERENCES MEMBER (member_id));

